# Generated by Django 2.2.12 on 2022-02-18 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='urlID',
            new_name='uuid',
        ),
    ]
