# Generated by Django 2.2.12 on 2022-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220218_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(max_length=10),
        ),
    ]
